#!/usr/bin/env bash
# Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-08-04 · Project: VideoFly
set -euo pipefail

root="$(cd "$(dirname "$0")/../.." && pwd)"
out="$root/quality/mechanical"
tmp="$out/.verify-tmp"
mkdir -p "$tmp"
trap 'rm -rf "$tmp"' EXIT

sed -n '/export type ProviderType =/,/;/p' "$root/src/ai/types.ts" \
  | grep -oE '"[^"]+"' | tr -d '"' > "$tmp/provider_defined.txt"

grep -m1 'includes(providerType)' \
  "$root/src/app/api/v1/video/callback/[provider]/route.ts" \
  | grep -oE '"[^"]+"' | tr -d '"' > "$tmp/provider_callback_handled.txt"

grep -Fvx -f "$tmp/provider_callback_handled.txt" "$tmp/provider_defined.txt" \
  > "$tmp/provider_callback_gap.txt" || true

diff -u "$out/provider_defined.txt" "$tmp/provider_defined.txt"
diff -u "$out/provider_callback_handled.txt" "$tmp/provider_callback_handled.txt"
diff -u "$out/provider_callback_gap.txt" "$tmp/provider_callback_gap.txt"

printf 'PASS: mechanical provider artifacts reproduce source exactly\n'
