# Generated by Quality Playbook v1.5.6 — Phase 6 summary spacing finalizer.
import os
from pathlib import Path

from docx import Document
from docx.shared import Pt


source = Path(os.environ["SUMMARY_DOC"])
output = Path(os.environ["SUMMARY_OUTPUT_DOC"])
doc = Document(source)
start = next(i for i, p in enumerate(doc.paragraphs) if p.text.strip().startswith("八、第 6 阶段："))
for paragraph in doc.paragraphs[start:]:
    if paragraph.style.name.startswith("Heading"):
        paragraph.paragraph_format.space_before = Pt(8)
        paragraph.paragraph_format.space_after = Pt(3)
    else:
        paragraph.paragraph_format.space_after = Pt(3)
        paragraph.paragraph_format.line_spacing = 1.0
doc.save(output)
print("DOCX_COMPACTED_PHASE6")
