# Generated by Quality Playbook v1.5.6 — Phase 6 summary finalizer.
import os
from pathlib import Path

from docx import Document
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor


DOCX = Path(os.environ["SUMMARY_DOC"])
OUTPUT_DOCX = Path(os.environ["SUMMARY_OUTPUT_DOC"])
NAVY = RGBColor(0x1F, 0x4D, 0x78)


def font(run, size=11, bold=False, color=None):
    run.font.name = "Calibri"
    rpr = run._element.get_or_add_rPr()
    rpr.rFonts.set(qn("w:ascii"), "Calibri")
    rpr.rFonts.set(qn("w:hAnsi"), "Calibri")
    rpr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    run.font.size = Pt(size)
    run.bold = bold
    if color is not None:
        run.font.color.rgb = color


def replace_lead(paragraph, label, text):
    paragraph.clear()
    font(paragraph.add_run(f"{label}："), bold=True, color=NAVY)
    font(paragraph.add_run(text))


doc = Document(DOCX)
for paragraph in doc.paragraphs:
    text = paragraph.text.strip()
    if text.startswith("第 6 阶段目标："):
        replace_lead(paragraph, "处置原则", "审计已经完成；后续工作是按风险批次实施修复并复核，不把未应用的拟议补丁当作已修复。")
    elif text.startswith("确认结果：确认 BUG-001 至 BUG-006"):
        replace_lead(paragraph, "第 3 阶段当时结论", "初步确认 BUG-001 至 BUG-006：2 个高、3 个中、1 个低；后续挑战审查撤回 BUG-001 与 BUG-003。")
    elif text.startswith("模式网格：") and "BUG-003" in text:
        replace_lead(paragraph, "第 3 阶段模式网格", "REQ-005 的 5 个积分状态单元均有补偿；REQ-007 的 2 个耐久对账缺口归入 BUG-002；REQ-011 的 Bailian 差异当时归入 BUG-003，后续确认其为轮询能力差异并撤回。")
    elif text.startswith("风险总量：当前有效 9 个问题"):
        replace_lead(paragraph, "第 4 阶段当时风险", "有效 9 个问题：3 高、5 中、1 低；第 5 阶段挑战审查随后撤回 BUG-003，最终有效问题为 8 个。")
    elif text.startswith("验证结果：10 项分诊探针"):
        replace_lead(paragraph, "第 4 阶段验证", "10 项分诊探针符合当时预期；完整测试 192 项、类型检查、Lint 和 19/19 补丁检查通过。")
    elif text.startswith("质量场景与自动检查：") and "Bailian" in text:
        replace_lead(paragraph, "质量场景与自动检查", "形成 10 个真实故障场景，新增 27 项 Vitest 功能测试并全部通过；机械脚本可重复提取 Provider 清单及 Bailian 回调差异，后续确认该差异对应轮询能力。")
    elif text == "十、审计文件位置":
        paragraph.paragraph_format.keep_with_next = True

doc.save(OUTPUT_DOCX)
print("DOCX_FINALIZED_PHASE6")
