# Generated by Quality Playbook v1.5.6 — Phase 6 summary render helper.
from pathlib import Path
import sys

import pypdfium2 as pdfium


pdf_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(r"F:\saas411\quality\docx-render-phase6\summary-phase6.pdf")
out_dir = pdf_path.parent
pdf = pdfium.PdfDocument(str(pdf_path))
for index in range(len(pdf)):
    image = pdf[index].render(scale=1.7).to_pil()
    image.save(out_dir / f"final-page-{index + 1}.png")
print(f"PAGES={len(pdf)}")
