// Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
// Author: Andrew Stellman · Date: 2026-08-04 · Project: VideoFly

import crypto from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { AI_PROVIDERS, parseProviderType } from "../src/ai/provider-config";
import {
  generateSignedCallbackUrl,
  verifyCallbackSignature,
} from "../src/ai/utils/callback-signature";
import {
  assertSafeRemoteMediaUrl,
  detectSupportedImageType,
} from "../src/lib/storage";
import { validateGenerationParams } from "../src/services/video-validation";

describe("Spec requirements", () => {
  it.each(AI_PROVIDERS)("REQ-011 accepts configured provider %s", (provider) => {
    expect(parseProviderType(provider)).toBe(provider);
  });

  it.each(["", "unknown", "evolink-extra", "KIE"])(
    "REQ-011 rejects unknown provider token %s",
    (provider) => expect(parseProviderType(provider)).toBeUndefined()
  );

  it("REQ-004 rejects a disabled catalog placeholder", () => {
    expect(() => validateGenerationParams({
      model: "seedance-2.5",
      duration: 5,
      mode: "text-to-video",
    })).toThrow(/Unsupported model/);
  });

  it("REQ-004 rejects unsupported model duration", () => {
    expect(() => validateGenerationParams({
      model: "seedance-1.5-pro",
      duration: 13,
      mode: "text-to-video",
    })).toThrow(/Unsupported duration/);
  });

  it("REQ-004 rejects images in text-to-video mode", () => {
    expect(() => validateGenerationParams({
      model: "seedance-2.0-mini",
      duration: 5,
      mode: "text-to-video",
      imageUrl: "https://example.com/input.png",
    })).toThrow(/does not accept an input image/);
  });

  it("REQ-004 requires an image in image-to-video mode", () => {
    expect(() => validateGenerationParams({
      model: "seedance-2.0-mini",
      duration: 5,
      mode: "image-to-video",
    })).toThrow(/requires one uploaded image/);
  });
});

describe("Fitness scenarios", () => {
  beforeEach(() => {
    process.env.CALLBACK_HMAC_SECRET = "quality-playbook-callback-secret-32-bytes";
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-08-04T00:00:00.000Z"));
  });

  afterEach(() => {
    vi.useRealTimers();
    process.env.CALLBACK_HMAC_SECRET = undefined;
  });

  it("Scenario 5 / REQ-006 accepts a fresh bound signature", () => {
    const url = new URL(generateSignedCallbackUrl("https://example.com/callback", "video-1"));
    expect(verifyCallbackSignature(
      "video-1",
      url.searchParams.get("ts")!,
      url.searchParams.get("sig")!
    )).toEqual({ valid: true });
  });

  it("Scenario 5 / REQ-006 rejects a signature replayed for another video", () => {
    const url = new URL(generateSignedCallbackUrl("https://example.com/callback", "video-1"));
    expect(verifyCallbackSignature(
      "video-2",
      url.searchParams.get("ts")!,
      url.searchParams.get("sig")!
    ).valid).toBe(false);
  });

  it("Scenario 5 / REQ-006 rejects excessive future clock skew", () => {
    const timestamp = String(Date.now() + 6 * 60 * 1000);
    const signature = crypto.createHmac("sha256", process.env.CALLBACK_HMAC_SECRET!)
      .update(`video-1:${timestamp}`).digest("hex");
    expect(verifyCallbackSignature("video-1", timestamp, signature)).toEqual({
      valid: false,
      error: "Signature timestamp is in the future",
    });
  });

  it("Scenario 9 / REQ-010 accepts a public HTTPS media URL", () => {
    expect(assertSafeRemoteMediaUrl("https://cdn.example.com/video.mp4").hostname)
      .toBe("cdn.example.com");
  });

  it("Scenario 10 / REQ-011 keeps the canonical provider set explicit", () => {
    expect([...AI_PROVIDERS]).toEqual(["evolink", "kie", "apimart", "bailian", "zhipu"]);
  });
});

describe("Boundaries and edge cases", () => {
  it.each([
    "http://cdn.example.com/video.mp4",
    "https://localhost/video.mp4",
    "https://127.0.0.1/video.mp4",
    "https://10.0.0.1/video.mp4",
    "https://192.168.1.1/video.mp4",
    "https://[::1]/video.mp4",
  ])("REQ-010 rejects unsafe remote destination %s", (url) => {
    expect(() => assertSafeRemoteMediaUrl(url)).toThrow();
  });

  it("REQ-010 rejects HTML disguised as an image", () => {
    expect(detectSupportedImageType(Buffer.from("<script>alert(1)</script>"))).toBeNull();
  });

  it("REQ-010 detects supported image magic bytes", () => {
    expect(detectSupportedImageType(Uint8Array.from([0xff, 0xd8, 0xff]))).toBe("image/jpeg");
    expect(detectSupportedImageType(Uint8Array.from([
      0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a,
    ]))).toBe("image/png");
  });

  it("REQ-006 rejects a weak callback secret", () => {
    process.env.CALLBACK_HMAC_SECRET = "too-short";
    expect(() => generateSignedCallbackUrl("https://example.com/callback", "video-1"))
      .toThrow(/at least 32 bytes/);
  });
});
