// Generated by Quality Playbook v1.5.6 — Phase 5 closure suite.
// Tests assert desired behavior and are strict expected failures until fixes land.

import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { expect, it } from "vitest";

const read = (path: string) => readFileSync(join(process.cwd(), path), "utf8");

export function test_bug_002_durable_exhaustion_reaches_terminal_policy() {
  const source = read("src/app/api/internal/workflows/video-reconcile/route.ts");
  expect(source).toContain("failGeneration");
  expect(source).not.toContain('status: "PENDING", reason: "reconciliation-window-exhausted"');
}

export function test_bug_004_callback_body_is_bounded_before_json_parse() {
  const source = read("src/app/api/v1/video/callback/[provider]/route.ts");
  expect(source).toContain("readRequestTextWithLimit");
  expect(source).not.toContain("await request.json()");
}

export function test_bug_005_active_guides_use_executable_callback_secret() {
  for (const path of ["README.md", "docs/API-INTEGRATION-GUIDE.md"]) {
    const text = read(path);
    expect(text).not.toContain("AI_CALLBACK_SECRET");
    expect(text).toContain("CALLBACK_HMAC_SECRET");
  }
}

export function test_bug_006_csp_allows_emitted_observability_scripts() {
  expect(read("src/app/layout.tsx")).toContain("<Analytics />");
  expect(read("src/app/layout.tsx")).toContain("<SpeedInsights />");
  expect(read("next.config.mjs")).toContain("https://va.vercel-scripts.com");
}

export function test_bug_007_media_fetch_binds_validated_dns_address() {
  const source = read("src/lib/storage.ts");
  expect(source).not.toContain('fetch(currentUrl, { redirect: "manual", signal })');
  expect(source).toMatch(/dispatcher|connect:\s*\{|lookup:\s*\(/);
}

export function test_bug_008_credit_transaction_vocabulary_is_total() {
  const route = read("src/app/api/v1/credit/history/route.ts");
  const mapping = route.slice(route.indexOf("const transTypeMapping"), route.indexOf("export async function GET"));
  const aliases = [...mapping.matchAll(/:\s*"([a-z_]+)"/g)].map((match) => match[1]);
  for (const entry of readdirSync(join(process.cwd(), "src/messages"), { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".json")) continue;
    const messages = JSON.parse(read(`src/messages/${entry.name}`));
    const keys = Object.keys(messages.dashboard.credits.types);
    expect(aliases.filter((alias) => !keys.includes(alias)), entry.name).toEqual([]);
  }
}

export function test_bug_009_workflow_enablement_requires_receiver_keys() {
  const source = read("src/lib/upstash.ts");
  expect(source).toContain("QSTASH_CURRENT_SIGNING_KEY");
  expect(source).toContain("QSTASH_NEXT_SIGNING_KEY");
}

export function test_bug_010_creation_filters_reach_request_and_service() {
  const hook = read("src/hooks/use-videos.ts");
  const request = hook.slice(hook.indexOf("apiClient.getVideos"), hook.indexOf("});", hook.indexOf("apiClient.getVideos")));
  expect(request).toContain("status:");
  expect(request).toContain("model:");
  expect(request).toContain("sortBy:");
  expect(read("src/services/video.ts")).toMatch(/options\?\.sortBy/);
}

it.fails("BUG-002 / REQ-007: durable exhaustion reaches a terminal policy", test_bug_002_durable_exhaustion_reaches_terminal_policy);
it.fails("BUG-004 / REQ-006: callback body is bounded before JSON parsing", test_bug_004_callback_body_is_bounded_before_json_parse);
it.fails("BUG-005 / REQ-012: active guides use the executable callback secret", test_bug_005_active_guides_use_executable_callback_secret);
it.fails("BUG-006 / REQ-014: CSP allows emitted observability scripts", test_bug_006_csp_allows_emitted_observability_scripts);
it.fails("BUG-007 / REQ-010: media fetch binds the validated DNS address", test_bug_007_media_fetch_binds_validated_dns_address);
it.fails("BUG-008 / REQ-013: credit transaction vocabulary is total", test_bug_008_credit_transaction_vocabulary_is_total);
it.fails("BUG-009 / REQ-007: workflow enablement requires receiver keys", test_bug_009_workflow_enablement_requires_receiver_keys);
it.fails("BUG-010 / REQ-013: creation filters reach request and service", test_bug_010_creation_filters_reach_request_and_service);
