# Generated by Quality Playbook v1.5.6 — Phase 4 summary updater.
from pathlib import Path

from docx import Document
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor


DOCX = Path(r"C:\Users\Administrator\Desktop\VideoFly网站全量质量检查阶段总结.docx")
NAVY = RGBColor(0x1F, 0x4D, 0x78)
RED = RGBColor(0x9B, 0x1C, 0x1C)


def font(run, size=11, bold=False, color=None):
    run.font.name = "Calibri"
    rpr = run._element.get_or_add_rPr()
    rpr.rFonts.set(qn("w:ascii"), "Calibri")
    rpr.rFonts.set(qn("w:hAnsi"), "Calibri")
    rpr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    run.font.size = Pt(size)
    run.bold = bold
    if color is not None:
        run.font.color.rgb = color


def replace_paragraph(paragraph, text, size=11, bold=False, color=None):
    paragraph.clear()
    font(paragraph.add_run(text), size=size, bold=bold, color=color)


def set_cell(cell, text, bold=False, color=None, size=9.2):
    paragraph = cell.paragraphs[0]
    replace_paragraph(paragraph, text, size=size, bold=bold, color=color)
    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER


def add_lead_before(anchor, label, text):
    paragraph = anchor.insert_paragraph_before()
    paragraph.paragraph_format.space_after = Pt(6)
    font(paragraph.add_run(f"{label}："), bold=True, color=NAVY)
    font(paragraph.add_run(text))


doc = Document(DOCX)

for paragraph in doc.paragraphs:
    text = paragraph.text.strip()
    if text == "阶段总结（累计更新至第 3 阶段）":
        replace_paragraph(paragraph, "阶段总结（累计更新至第 4 阶段）", size=14, color=RGBColor(0x66, 0x66, 0x66))
    elif text.startswith("阶段性判断："):
        replace_paragraph(paragraph, "阶段性判断：规格审计撤回了原支付死链结论，并确认 DNS 连接绑定、QStash 配置、积分流水显示和作品筛选四项新问题。")
        font(paragraph.runs[0], bold=False)
    elif text.startswith("证据强度："):
        replace_paragraph(paragraph, "证据强度：三份独立视角报告、1 份综合分诊和 10 项可执行探针已完成；所有事实争议均以代码断言裁决。")
    elif text.startswith("基线结果："):
        replace_paragraph(paragraph, "基线结果：完整测试 192 项，其中 184 项正常通过、8 项为预期失败证据；类型检查、Lint 和 19 个补丁可应用性检查全部通过。")
    elif text == "六、下一阶段计划":
        replace_paragraph(paragraph, "七、下一阶段计划", size=16, bold=True, color=RGBColor(0x2E, 0x74, 0xB5))
    elif text == "七、审计文件位置":
        replace_paragraph(paragraph, "八、审计文件位置", size=16, bold=True, color=RGBColor(0x2E, 0x74, 0xB5))
    elif text.startswith("第 4 阶段目标："):
        replace_paragraph(paragraph, "第 5 阶段目标：逐项执行红绿 TDD，清理撤回项，验证拟议修复并形成最终闭环清单。")

meta = doc.tables[0]
set_cell(meta.cell(1, 1), "6 个阶段中已完成 4 个：探索、质量制品生成、代码审查、规格审计", size=11)
set_cell(meta.cell(2, 1), "有效确认 9 个问题：3 个高、5 个中、1 个低；另撤回 1 个误报；尚未修改产品源码", size=11)
set_cell(meta.cell(3, 1), "第 5 阶段对账与 TDD：逐项证明问题、验证修复并完成闭环", size=11)

findings_table = doc.tables[1]
rows = [
    ("撤回", "Stripe /dashboard 死链", "中间件会重定向到 /text-to-video；原 404 前提不成立。", "REQ-009 / BUG-001"),
    ("高", "长任务对账窗口耗尽后悬挂", "约 7.5 分钟后返回 PENDING，视频与冻结积分可能长期非终态。", "REQ-005、007 / BUG-002"),
    ("中", "Bailian 轮询能力未显式声明", "当前请求转换不提交 callbackUrl，但接口与白名单无法机械区分轮询专用。", "REQ-011 / BUG-003"),
    ("中", "AI 回调请求体没有应用级上限", "自托管时可无限解析；平台部署也缺少与 Stripe 一致的 1 MiB 防线。", "REQ-006、010 / BUG-004"),
    ("中", "回调密钥文档变量不一致", "部分指南使用代码从不读取的 AI_CALLBACK_SECRET。", "REQ-012 / BUG-005"),
    ("低", "CSP 拦截 Vercel 观测脚本", "Analytics 与 Speed Insights 无法采集，削弱事故诊断。", "BUG-006"),
    ("高", "DNS 校验未绑定实际媒体连接", "校验后 fetch 再次按主机名解析，存在重绑定访问私网的条件风险。", "REQ-010 / BUG-007"),
    ("中", "积分流水类型在 API/UI/翻译间不一致", "常见消费、退款与调整记录可能显示缺失翻译或原始标识。", "REQ-005、013 / BUG-008"),
    ("高", "QStash 调度端与接收端密钥要求不同", "任务可被发往必然返回 503 的恢复入口，错失回调后无法耐久收敛。", "REQ-007、012 / BUG-009"),
    ("中", "作品筛选控件未传递筛选条件", "状态、模型和排序选择均返回相同的未筛选结果。", "REQ-013 / BUG-010"),
    ("覆盖缺口", "缺少付费生成完整链路测试", "尚无单一确定性流程覆盖会话、冻结、Provider、存储、结算和账户响应。", "CAND-008"),
]
while len(findings_table.rows) < len(rows) + 1:
    findings_table.add_row()
for row, values in zip(findings_table.rows[1:], rows):
    for index, value in enumerate(values):
        color = RED if index == 0 and values[0] == "高" else None
        set_cell(row.cells[index], value, bold=index == 0, color=color)

next_heading = next(p for p in doc.paragraphs if p.text.strip() == "七、下一阶段计划")
phase4_heading = next_heading.insert_paragraph_before("六、第 4 阶段：规格审计与分诊", style="Heading 1")
phase4_heading.paragraph_format.keep_with_next = True
add_lead_before(next_heading, "独立审计", "从产品运营、安全财务、实现一致性三个视角复核全部 12 条基线需求，并补充 REQ-013 前后端数据契约。")
add_lead_before(next_heading, "重要纠偏", "BUG-001 已撤回：/dashboard 由中间件实现为重定向；旧回归和修复补丁均标记为不得应用。")
add_lead_before(next_heading, "新增确认", "新增 BUG-007 至 BUG-010：DNS 连接绑定、积分流水词汇、QStash 密钥一致性和作品筛选链路。")
add_lead_before(next_heading, "风险总量", "当前有效 9 个问题：3 高、5 中、1 低；其中 BUG-007 暂不生成网络修复补丁，避免未经验证地破坏代理、重定向或流式下载。")
add_lead_before(next_heading, "验证结果", "10 项分诊探针全部符合预期；完整测试 192 项、类型检查、Lint 和 19/19 补丁检查通过。")
add_lead_before(next_heading, "引用复核", "本轮 13 条需求全部为代码推导，Tier 1/2 引用数量为 0，因此语义引用检查按协议为空结果，不伪造跨模型投票。")

plan_items = [
    "对 9 个有效问题逐项执行红阶段回归，确认测试在当前代码上以预期方式失败。",
    "对已有修复补丁执行绿阶段验证；BUG-007 先完成连接固定方案评审，再决定是否实现。",
    "清理 BUG-001 的撤回补丁与旧写案冲突，确保执行证据、问题清单和总结一致。",
    "补齐独立问题写案、TDD 日志、追踪表和完整性报告，形成可直接统一修改的闭环清单。",
]
plan_heading_index = next(
    index for index, paragraph in enumerate(doc.paragraphs)
    if paragraph.text.strip() == "七、下一阶段计划"
)
following = doc.paragraphs[plan_heading_index + 1:]
bullets = [p for p in following if p.style.name == "List Bullet"][:4]
for paragraph, text in zip(bullets, plan_items):
    replace_paragraph(paragraph, text)

doc.save(DOCX)
print("DOCX_UPDATED")
