# Generated by Quality Playbook v1.5.6 — Phase 6 summary updater.
import os
from pathlib import Path

from docx import Document
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor


DOCX = Path(os.environ["SUMMARY_DOC"])
OUTPUT_DOCX = Path(os.environ["SUMMARY_OUTPUT_DOC"])
NAVY = RGBColor(0x1F, 0x4D, 0x78)
RED = RGBColor(0x9B, 0x1C, 0x1C)
BLUE = RGBColor(0x2E, 0x74, 0xB5)
GRAY = RGBColor(0x66, 0x66, 0x66)


def font(run, size=11, bold=False, color=None):
    run.font.name = "Calibri"
    rpr = run._element.get_or_add_rPr()
    rpr.rFonts.set(qn("w:ascii"), "Calibri")
    rpr.rFonts.set(qn("w:hAnsi"), "Calibri")
    rpr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    run.font.size = Pt(size)
    run.bold = bold
    if color is not None:
        run.font.color.rgb = color


def replace_paragraph(paragraph, text, size=11, bold=False, color=None):
    paragraph.clear()
    font(paragraph.add_run(text), size=size, bold=bold, color=color)


def set_cell(cell, text, bold=False, color=None, size=9.2):
    replace_paragraph(cell.paragraphs[0], text, size=size, bold=bold, color=color)
    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER


def add_lead_before(anchor, label, text):
    paragraph = anchor.insert_paragraph_before()
    paragraph.paragraph_format.space_after = Pt(6)
    font(paragraph.add_run(f"{label}："), bold=True, color=NAVY)
    font(paragraph.add_run(text))


doc = Document(DOCX)
if any(p.text.strip().startswith("八、第 6 阶段：") for p in doc.paragraphs):
    raise RuntimeError("Phase 6 summary already exists; refusing to append twice")

for paragraph in doc.paragraphs:
    text = paragraph.text.strip()
    if text == "阶段总结（累计更新至第 5 阶段）":
        replace_paragraph(paragraph, "阶段总结（累计更新至第 6 阶段，全部完成）", size=14, color=GRAY)
    elif text.startswith("阶段性判断："):
        replace_paragraph(paragraph, "阶段性判断：全量审计 6 个阶段均已完成；8 个有效问题全部复现，审计制品最终门禁通过，但产品仍不具备发布条件。")
    elif text.startswith("证据强度："):
        replace_paragraph(paragraph, "证据强度：27 项功能测试、完整 200 项测试、生产构建、类型检查、Lint、机械复核、19 个补丁检查和最终质量门禁均有运行凭证。")
    elif text.startswith("基线结果："):
        replace_paragraph(paragraph, "最终结果：质量门禁 93 条通过记录、0 项失败、3 条旧清单兼容提醒；8 个问题中 6 个拟议修复通过 GREEN，1 个不完整，1 个无获批补丁。")
    elif text == "八、下一阶段计划":
        replace_paragraph(paragraph, "九、后续处置建议", size=16, bold=True, color=BLUE)
    elif text == "九、审计文件位置":
        replace_paragraph(paragraph, "十、审计文件位置", size=16, bold=True, color=BLUE)

meta = doc.tables[0]
set_cell(meta.cell(1, 1), "6 个阶段已全部完成：探索、质量制品、代码审查、规格审计、对账与 TDD、最终验证", size=11)
set_cell(meta.cell(2, 1), "有效确认 8 个问题：3 个高、4 个中、1 个低；2 个历史发现已驳回；产品源码保持不变", size=11)
set_cell(meta.cell(3, 1), "审计工作已结束；当前建议先统一修复并复核，再决定是否发布", size=11)

for row in doc.tables[1].rows[1:]:
    if "Bailian 回调入口缺失" in row.cells[1].text:
        set_cell(row.cells[2], "代码实现轮询完成路径，且仓库契约未要求所有 Provider 支持回调；早期文档引用已撤回。")
        set_cell(row.cells[3], "Finding 003 / 已关闭")

for paragraph in doc.paragraphs:
    text = paragraph.text.strip()
    if text.startswith("挑战复核：") and "Bailian" in text:
        replace_paragraph(paragraph, "挑战复核：对所有触发项执行两轮反方审查；Bailian 已实现轮询，仓库契约未要求回调入口，因此该发现被驳回；早期引用的 Provider 对照表与 Bailian 无关，已在最终核验中撤回。")

next_heading = next(p for p in doc.paragraphs if p.text.strip() == "九、后续处置建议")
phase6_heading = next_heading.insert_paragraph_before("八、第 6 阶段：最终验证与交付门禁", style="Heading 1")
phase6_heading.paragraph_format.keep_with_next = True
add_lead_before(next_heading, "机械闭环", "严格重跑原始 Bash 提取验证，Provider 清单制品与当前源码完全一致，退出码为 0。")
add_lead_before(next_heading, "最终门禁", "Quality Playbook 最终门禁记录 93 条 PASS、0 条 FAIL、3 条旧版清单兼容 WARN；警告不代表产品功能通过。")
add_lead_before(next_heading, "完整验证", "27/27 功能测试通过；全量测试 184 项通过、16 项预期失败；类型检查、Lint 和 Next.js 生产构建通过。")
add_lead_before(next_heading, "制品修正", "清理两处被后续证据推翻的旧描述，撤回不适用于 Bailian 的规格引用；补齐 111 行字段参考表、结构化集成结果、JUnit 与写后校验要求。")
add_lead_before(next_heading, "一致性检查", "14 条需求在需求文档、覆盖矩阵与进度记录中的数量一致；8 个问题、测试、补丁、写案和日志均可相互追踪。")
add_lead_before(next_heading, "发布判断", "审计流程已完成，但发布建议仍为 BLOCK：3 个高风险问题尚未进入产品源码，BUG-007 无获批修复，BUG-008 补丁仍不完整。")
add_lead_before(next_heading, "源码状态", "主工作区没有产品源码修改；所有变更仅位于 quality 审计目录和本累计总结文档。")

plan_items = [
    "优先处理 BUG-002、BUG-007、BUG-009 三个高风险问题，并由负责人确认长任务超时和 DNS 连接固定方案。",
    "随后处理 BUG-004、BUG-005、BUG-008、BUG-010 与 BUG-006；BUG-008 必须补齐 payment_reversal 的全部语言翻译。",
    "修复应分批应用，每批运行对应回归测试、完整测试、类型检查、Lint、生产构建和质量门禁。",
    "真实 Provider、支付、数据库和存储链路必须在获批的可清理测试环境中验证；缺少授权时继续保持 BLOCK。",
]
heading_index = next(i for i, p in enumerate(doc.paragraphs) if p.text.strip() == "九、后续处置建议")
bullets = [p for p in doc.paragraphs[heading_index + 1:] if p.style.name == "List Bullet"][:4]
for paragraph, text in zip(bullets, plan_items):
    replace_paragraph(paragraph, text)

doc.save(OUTPUT_DOCX)
print("DOCX_UPDATED_PHASE6")
