# Generated by Quality Playbook v1.5.6 — Phase 5 summary updater.
import os
from pathlib import Path

from docx import Document
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor


DOCX = Path(os.environ["SUMMARY_DOC"])
OUTPUT_DOCX = Path(os.environ.get("SUMMARY_OUTPUT_DOC", str(DOCX)))
NAVY = RGBColor(0x1F, 0x4D, 0x78)
RED = RGBColor(0x9B, 0x1C, 0x1C)
BLUE = RGBColor(0x2E, 0x74, 0xB5)
GRAY = RGBColor(0x66, 0x66, 0x66)


def font(run, size=11, bold=False, color=None):
    run.font.name = "Calibri"
    rpr = run._element.get_or_add_rPr()
    rpr.rFonts.set(qn("w:ascii"), "Calibri")
    rpr.rFonts.set(qn("w:hAnsi"), "Calibri")
    rpr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    run.font.size = Pt(size)
    run.bold = bold
    if color is not None:
        run.font.color.rgb = color


def replace_paragraph(paragraph, text, size=11, bold=False, color=None):
    paragraph.clear()
    font(paragraph.add_run(text), size=size, bold=bold, color=color)


def set_cell(cell, text, bold=False, color=None, size=9.2):
    replace_paragraph(cell.paragraphs[0], text, size=size, bold=bold, color=color)
    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER


def add_lead_before(anchor, label, text):
    paragraph = anchor.insert_paragraph_before()
    paragraph.paragraph_format.space_after = Pt(6)
    font(paragraph.add_run(f"{label}："), bold=True, color=NAVY)
    font(paragraph.add_run(text))


doc = Document(DOCX)
if any(p.text.strip().startswith("七、第 5 阶段：") for p in doc.paragraphs):
    raise RuntimeError("Phase 5 summary already exists; refusing to append twice")

for paragraph in doc.paragraphs:
    text = paragraph.text.strip()
    if text == "阶段总结（累计更新至第 4 阶段）":
        replace_paragraph(paragraph, "阶段总结（累计更新至第 5 阶段）", size=14, color=GRAY)
    elif text.startswith("阶段性判断："):
        replace_paragraph(paragraph, "阶段性判断：8 个有效问题均已复现；6 个拟议修复通过红绿验证，1 个修复仍不完整，1 个高风险网络问题尚无获批补丁。")
    elif text.startswith("证据强度："):
        replace_paragraph(paragraph, "证据强度：每个有效问题均有命名回归测试和 RED 日志；有修复补丁的项目均执行隔离 GREEN 验证，未用叙述代替运行证据。")
    elif text.startswith("基线结果："):
        replace_paragraph(paragraph, "基线结果：完整测试 200 项，其中 184 项正常通过、16 项为预期失败；类型检查、Lint、机械验证、19 个补丁检查和终端质量门禁全部通过。")
    elif text == "三、当前确认问题与待审项":
        replace_paragraph(paragraph, "三、当前确认问题与闭环状态", size=16, bold=True, color=BLUE)
    elif text == "七、下一阶段计划":
        replace_paragraph(paragraph, "八、下一阶段计划", size=16, bold=True, color=BLUE)
    elif text == "八、审计文件位置":
        replace_paragraph(paragraph, "九、审计文件位置", size=16, bold=True, color=BLUE)
    elif text.startswith("第 5 阶段目标："):
        replace_paragraph(paragraph, "第 6 阶段目标：执行最终一致性、自检基准和交付门禁，确认所有审计制品可追踪且互不矛盾。")

meta = doc.tables[0]
set_cell(meta.cell(1, 1), "6 个阶段中已完成 5 个：探索、质量制品生成、代码审查、规格审计、对账与 TDD", size=11)
set_cell(meta.cell(2, 1), "有效确认 8 个问题：3 个高、4 个中、1 个低；另有 2 个已驳回历史发现；产品源码保持不变", size=11)
set_cell(meta.cell(3, 1), "第 6 阶段最终验证：检查制品一致性、版本、追踪关系与收敛状态", size=11)

rows = [
    ("驳回", "Stripe /dashboard 死链", "中间件已实现可用重定向；原结论是路由枚举误判。", "Finding 001 / 已关闭"),
    ("高", "长任务对账窗口耗尽后悬挂", "当前代码已 RED；拟议 60 分钟终止策略已 GREEN，业务超时仍需确认。", "REQ-007 / BUG-002"),
    ("驳回", "Bailian 回调入口缺失", "项目规格明确不支持回调且已实现轮询；原通用白名单补丁不应应用。", "Finding 003 / 已关闭"),
    ("中", "AI 回调请求体没有应用级上限", "当前代码已 RED；1 MiB 有界读取补丁已 GREEN。", "REQ-006 / BUG-004"),
    ("中", "回调密钥文档变量不一致", "当前指南已 RED；统一为 CALLBACK_HMAC_SECRET 的补丁已 GREEN。", "REQ-012 / BUG-005"),
    ("低", "CSP 拦截 Vercel 观测脚本", "当前策略已 RED；允许精确脚本源的补丁已 GREEN。", "REQ-014 / BUG-006"),
    ("高", "DNS 校验未绑定实际媒体连接", "当前代码已 RED；尚无安全补丁，需先解决连接固定、代理与重定向兼容。", "REQ-010 / BUG-007"),
    ("中", "积分流水类型在 API/UI/翻译间不一致", "当前代码已 RED；拟议补丁 GREEN 失败，仍漏 payment_reversal 翻译。", "REQ-013 / BUG-008"),
    ("高", "QStash 调度端与接收端密钥要求不同", "当前代码已 RED；统一完整配置判断的补丁已 GREEN。", "REQ-007、012 / BUG-009"),
    ("中", "作品筛选控件未传递筛选条件", "当前代码已 RED；贯通状态、模型与排序的补丁已 GREEN。", "REQ-013 / BUG-010"),
    ("覆盖缺口", "缺少付费生成完整链路测试", "真实 Provider、支付和存储联调仍需授权环境；当前本地证据不冒充线上验证。", "CAND-008 / 保留"),
]
table = doc.tables[1]
for row, values in zip(table.rows[1:], rows):
    for index, value in enumerate(values):
        set_cell(row.cells[index], value, bold=index == 0, color=RED if index == 0 and value == "高" else None)

next_heading = next(p for p in doc.paragraphs if p.text.strip() == "八、下一阶段计划")
phase5_heading = next_heading.insert_paragraph_before("七、第 5 阶段：对账、挑战复核与 TDD 闭环", style="Heading 1")
phase5_heading.paragraph_format.keep_with_next = True
add_lead_before(next_heading, "挑战复核", "对所有触发项执行两轮反方审查；Bailian 回调发现因规格明确标注为轮询专用而被驳回，有效问题由 9 个调整为 8 个。")
add_lead_before(next_heading, "回归闭环", "8 个有效问题全部获得命名回归测试并在未修改代码上产生 RED 证据；回归套件使用严格预期失败标记，不污染正常 CI。")
add_lead_before(next_heading, "绿灯验证", "BUG-002、004、005、006、009、010 的拟议补丁通过 GREEN；BUG-008 的补丁仍漏支付撤销翻译，明确记录为 GREEN 失败。")
add_lead_before(next_heading, "安全保留", "BUG-007 只确认缺陷、不批准仓促修复；连接固定方案必须同时兼容代理、逐跳重定向校验、流式限额和连接资源释放。")
add_lead_before(next_heading, "需求对账", "新增 REQ-014 约束已启用观测脚本与 CSP 的一致性；8 个有效问题现均可追溯到明确需求。")
add_lead_before(next_heading, "门禁结果", "质量门禁 0 项失败；完整测试 184 项通过、16 项预期失败，类型检查、Lint、机械验证和 19/19 补丁检查通过。")
add_lead_before(next_heading, "源码状态", "所有红绿验证均在一次性隔离工作区完成并清理；主工作区仅新增 quality 审计制品，没有修改网站产品源码。")

plan_items = [
    "运行最终制品自检，核对需求、问题、测试、补丁、写案、日志和索引之间的数量与引用关系。",
    "检查所有 Quality Playbook 版本标记、JSON 架构、阶段事件和最终收敛结论是否一致。",
    "确认执行证据与叙述无矛盾，并对仍开放或修复不完整的项目保持 BLOCK 状态。",
    "完成后给出可统一实施的修复批次建议；是否实际修改产品源码由用户另行决定。",
]
heading_index = next(i for i, p in enumerate(doc.paragraphs) if p.text.strip() == "八、下一阶段计划")
bullets = [p for p in doc.paragraphs[heading_index + 1:] if p.style.name == "List Bullet"][:4]
for paragraph, text in zip(bullets, plan_items):
    replace_paragraph(paragraph, text)

doc.save(OUTPUT_DOCX)
print("DOCX_UPDATED_PHASE5")
