# Generated by Quality Playbook v1.5.6 — Phase 6 DOCX structural verifier.
import sys

from docx import Document


doc = Document(sys.argv[1])
text = "\n".join(paragraph.text for paragraph in doc.paragraphs)
needles = [
    "累计更新至第 6 阶段",
    "八、第 6 阶段：最终验证与交付门禁",
    "九、后续处置建议",
    "十、审计文件位置",
    "93 条 PASS",
    "111 行字段参考表",
]
for needle in needles:
    if needle not in text:
        raise AssertionError(f"missing summary text: {needle}")
if text.count("八、第 6 阶段：最终验证与交付门禁") != 1:
    raise AssertionError("Phase 6 heading count is not one")
print(f"DOCX_STRUCTURE=PASS PARAGRAPHS={len(doc.paragraphs)} TABLES={len(doc.tables)}")
