// Generated by Quality Playbook v1.5.6 — Phase 4 triage probes.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const root = process.cwd();
const source = (path: string) => readFileSync(resolve(root, path), "utf8");

describe("Phase 4 executable triage probes", () => {
  it("rejects the BUG-001 404 claim: middleware lines 12 and 41 redirect /dashboard", () => {
    const body = source("src/middleware.ts");
    expect(body).toContain('"/dashboard": "/text-to-video"');
    expect(body).toContain("return NextResponse.redirect(url)");
    expect(body).toContain('"/((?!api|_next|.*\\\\..*).*)"');
  });

  it("verifies BUG-002 fix: exhaustion no longer returns PENDING", () => {
    const body = source("src/app/api/internal/workflows/video-reconcile/route.ts");
    expect(body).not.toContain('return { status: "PENDING", reason: "reconciliation-window-exhausted" }');
  });

  it("establishes BUG-003 intent facts: Bailian line 397 omits callbackUrl and ingress line 16 rejects it", () => {
    const mapping = source("src/ai/model-mapping.ts");
    const transformer = mapping.slice(
      mapping.indexOf("function bailianParamsTransformer"),
      mapping.indexOf("// ============================================================================", mapping.indexOf("function bailianParamsTransformer"))
    );
    const callback = source("src/app/api/v1/video/callback/[provider]/route.ts");
    expect(transformer).not.toContain("callbackUrl");
    expect(callback).toContain('["evolink", "kie", "apimart", "zhipu"]');
  });

  it("verifies BUG-004 fix: callback JSON uses a bounded reader", () => {
    const body = source("src/app/api/v1/video/callback/[provider]/route.ts");
    expect(body).toContain("readRequestTextWithLimit");
    expect(body).not.toContain("await request.json()");
  });

  it("verifies BUG-005 fix: callback secret name matches executable code", () => {
    expect(source("README.md")).not.toContain("AI_CALLBACK_SECRET");
    expect(source("docs/API-INTEGRATION-GUIDE.md")).not.toContain("AI_CALLBACK_SECRET");
  });

  it("verifies BUG-006 fix: CSP allows the emitted Vercel script origin", () => {
    const layout = source("src/app/layout.tsx");
    const config = source("next.config.mjs");
    expect(layout).toContain("<Analytics />");
    expect(layout).toContain("<SpeedInsights />");
    expect(config).toContain("https://va.vercel-scripts.com");
  });

  it("verifies BUG-007 fix: fetch binds to a validated DNS answer", () => {
    const body = source("src/lib/storage.ts");
    expect(body).not.toContain('fetch(currentUrl, { redirect: "manual", signal })');
    expect(body).toContain("createPinnedLookup");
    expect(body).toContain("lookup: createPinnedLookup(address)");
    expect(body).toContain("undiciFetch(target.url");
    expect(body).toContain("dispatcher");
  });

  it("verifies BUG-008 fix: every API alias has a locale key", () => {
    const route = source("src/app/api/v1/credit/history/route.ts");
    const mappingBlock = route.slice(route.indexOf("const transTypeMapping"), route.indexOf("export async function GET"));
    const aliases = [...mappingBlock.matchAll(/:\s*"([a-z_]+)"/g)].map((match) => match[1]);
    const messages = JSON.parse(source("src/messages/en.json"));
    const keys = Object.keys(messages.dashboard.credits.types);
    expect(aliases.filter((alias) => !keys.includes(alias))).toEqual([]);
  });

  it("verifies BUG-009 fix: scheduler and handler require the same credentials", () => {
    const scheduler = source("src/lib/upstash.ts");
    expect(scheduler).toContain("QSTASH_CURRENT_SIGNING_KEY");
    expect(scheduler).toContain("QSTASH_NEXT_SIGNING_KEY");
  });

  it("verifies BUG-010 fix: status/model/sort reach the list contract", () => {
    const hook = source("src/hooks/use-videos.ts");
    const query = hook.slice(hook.indexOf("apiClient.getVideos"), hook.indexOf("});", hook.indexOf("apiClient.getVideos")));
    expect(query).toContain("status:");
    expect(query).toContain("model:");
    expect(query).toContain("sortBy:");
  });
});
