// Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
// Author: Andrew Stellman · Date: 2026-08-04 · Project: VideoFly

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";

const { handleCallback } = vi.hoisted(() => ({
  handleCallback: vi.fn(async () => undefined),
}));

vi.mock("@/services/video", () => ({ videoService: { handleCallback } }));
vi.mock("@/ai/utils/callback-signature", () => ({
  verifyCallbackSignature: () => ({ valid: true }),
}));

import { POST as callbackPost } from "../../src/app/api/v1/video/callback/[provider]/route";

const root = process.cwd();
const source = (path: string) => readFileSync(join(root, path), "utf8");

describe("Phase 3 confirmation probes", () => {
  it("CAND-001 dismissal remains valid because middleware implements /dashboard", () => {
    const middleware = source("src/middleware.ts");
    expect(middleware).toContain('"/dashboard": "/text-to-video"');
    expect(middleware).toContain("NextResponse.redirect");
  });

  it("CAND-002 fix gives durable reconciliation a terminal timeout", () => {
    const workflow = source("src/app/api/internal/workflows/video-reconcile/route.ts");
    expect(workflow).toContain("attempt < 80");
    expect(workflow).toContain("failGeneration");
    expect(workflow).not.toContain(
      'status: "PENDING", reason: "reconciliation-window-exhausted"'
    );
  });

  it("CAND-003 dismissal preserves the supported polling-only Bailian contract", async () => {
    const request = new NextRequest(
      "https://example.com/api/v1/video/callback/bailian?videoUuid=vid-1&ts=1&sig=valid",
      { method: "POST", body: JSON.stringify({ task_id: "task-1" }) }
    );
    const response = await callbackPost(request, {
      params: Promise.resolve({ provider: "bailian" }),
    });
    expect(response.status).toBe(400);
    expect(handleCallback).not.toHaveBeenCalled();
  });

  it("CAND-004 fix rejects a callback payload over 1 MiB", async () => {
    handleCallback.mockClear();
    const consoleError = vi
      .spyOn(console, "error")
      .mockImplementation(() => undefined);
    const request = new NextRequest(
      "https://example.com/api/v1/video/callback/evolink?videoUuid=vid-1&ts=1&sig=valid",
      {
        method: "POST",
        body: JSON.stringify({ padding: "x".repeat(1024 * 1024 + 1) }),
      }
    );
    const response = await callbackPost(request, {
      params: Promise.resolve({ provider: "evolink" }),
    });
    expect(response.status).toBe(413);
    expect(handleCallback).not.toHaveBeenCalled();
    consoleError.mockRestore();
  });

  it("CAND-006 fix aligns active guides with the executable callback secret", () => {
    expect(source("README.md")).not.toContain("AI_CALLBACK_SECRET");
    expect(source("docs/API-INTEGRATION-GUIDE.md")).not.toContain("AI_CALLBACK_SECRET");
    expect(source("src/ai/utils/callback-signature.ts")).toContain("CALLBACK_HMAC_SECRET");
  });

  it("CAND-007 fix allows emitted Vercel scripts in CSP", () => {
    const layout = source("src/app/layout.tsx");
    const config = source("next.config.mjs");
    expect(layout).toContain("<Analytics />");
    expect(layout).toContain("<SpeedInsights />");
    expect(config).toContain("va.vercel-scripts.com");
  });
});
