// Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
// Author: Andrew Stellman · Date: 2026-08-04 · Project: VideoFly

import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";

const { handleCallback } = vi.hoisted(() => ({
  handleCallback: vi.fn(async () => undefined),
}));

vi.mock("@/services/video", () => ({ videoService: { handleCallback } }));
vi.mock("@/ai/utils/callback-signature", () => ({
  verifyCallbackSignature: () => ({ valid: true }),
}));

import { POST as callbackPost } from "../../src/app/api/v1/video/callback/[provider]/route";

const root = process.cwd();
const source = (path: string) => readFileSync(join(root, path), "utf8");

describe("Phase 3 confirmation probes", () => {
  it("CAND-001 confirms every subscription flow returns to missing /dashboard", () => {
    const billing = source("src/services/billing.ts");
    const pageFiles: string[] = [];
    const walk = (dir: string) => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const path = join(dir, entry.name);
        if (entry.isDirectory()) walk(path);
        else if (entry.name === "page.tsx") pageFiles.push(path.replaceAll("\\", "/"));
      }
    };
    walk(join(root, "src/app"));
    expect(billing.match(/\/dashboard/g)?.length).toBeGreaterThanOrEqual(4);
    expect(pageFiles.some((path) => /\/dashboard\/page\.tsx$/.test(path))).toBe(false);
    expect(pageFiles.some((path) => /\/settings\/page\.tsx$/.test(path))).toBe(true);
  });

  it("CAND-002 confirms durable reconciliation ends nonterminal after ten attempts", () => {
    const workflow = source("src/app/api/internal/workflows/video-reconcile/route.ts");
    expect(workflow).toContain("attempt < 10");
    expect(workflow).toContain('return { status: "PENDING", reason: "reconciliation-window-exhausted" }');
    expect(workflow).not.toMatch(/scheduleVideoReconciliation|failGeneration|creditService\.release/);
  });

  it("CAND-003 confirms a valid Bailian callback is rejected before handling", async () => {
    const request = new NextRequest(
      "https://example.com/api/v1/video/callback/bailian?videoUuid=vid-1&ts=1&sig=valid",
      { method: "POST", body: JSON.stringify({ task_id: "task-1" }) }
    );
    const response = await callbackPost(request, {
      params: Promise.resolve({ provider: "bailian" }),
    });
    expect(response.status).toBe(400);
    expect(handleCallback).not.toHaveBeenCalled();
  });

  it("CAND-004 confirms a payload over 1 MiB reaches callback handling", async () => {
    handleCallback.mockClear();
    const request = new NextRequest(
      "https://example.com/api/v1/video/callback/evolink?videoUuid=vid-1&ts=1&sig=valid",
      {
        method: "POST",
        body: JSON.stringify({ padding: "x".repeat(1024 * 1024 + 1) }),
      }
    );
    const response = await callbackPost(request, {
      params: Promise.resolve({ provider: "evolink" }),
    });
    expect(response.status).toBe(200);
    expect(handleCallback).toHaveBeenCalledOnce();
  });

  it("CAND-006 confirms active guides use a non-executable callback secret name", () => {
    expect(source("README.md")).toContain("AI_CALLBACK_SECRET");
    expect(source("docs/API-INTEGRATION-GUIDE.md")).toContain("AI_CALLBACK_SECRET");
    expect(source("src/ai/utils/callback-signature.ts")).toContain("CALLBACK_HMAC_SECRET");
  });

  it("CAND-007 confirms emitted Vercel scripts are absent from CSP", () => {
    const layout = source("src/app/layout.tsx");
    const config = source("next.config.mjs");
    expect(layout).toContain("<Analytics />");
    expect(layout).toContain("<SpeedInsights />");
    expect(config).not.toContain("va.vercel-scripts.com");
  });
});
